sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cpMg6MGjte4CVXMV1VZfTGAPSazN/TmAauLgzZd5wJH52RtA/2+c+FLDM1fecBvSZUsBl+DZsBuiPdr2PVNxT59wuB0784RNrB/TP8NWfhE7VKj0G9L5VUUy36fEps3on3YUCC4MDjA9wmkDnznjoiwL+dBD0V9gsf05qxA4xi/NumUM1fLU6+rqI/+/xIllEBfefUL2nM3CLTTvxamdHYtS4jJI1daGly22GjR5ERowf/8Vpsvxr0e9rJVi/9Z3m8Dq9MmD9VkVhA6QWv0svnROwQC315u4/3S/2KaCKRVlwhFUGUSzhvgUkIIGsmcX0hbDp7y9YMhySvSV/OyD5alll9YYQDQEZpASsSyoIcNEoRWBTkzNNr5rEL0wOHJEmFUGy9uu+Tdb2cLB1I5dsbEK5FEQ10Xicpzcd5gm6Dxvfg5k8Rql0/0s2/BwtZRnRSBXuEupXxaYaZgFfz84xJO3ZPJmr/x8qw/Qx2Mvuq56fd/JhvfFxfzzxBbxOaf1tPs9BRwZ0U3f4hdSxhNRdE5VyRYrtbaJICECZlVRdtMcFBH+xE9eDw1d5JU9ImH6/9x0yuil3A5WcsH8okK4C3ckRehuZuzkDTp7nQdFm8GUd8O8Naq/SB6HTnSy21/UvDYAD4fTGuDy4kVtXy/J53bOnqFn26g6yUNje01+EGM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/In-the-Fire-of-the-Forge--A-Romance-of-Old-Nuremberg---Complete_5551
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy